INSERT INTO `settings` (`option_key`, `option_name`, `option_value`)
VALUES
('support_center_contact_number', 'شماره تماس با مرکز پشتیبانی', '02591010100'),
('support_contact_number', 'شماره تماس با پشتیبانی', '09123753475'),
('eitaa_channel', 'کانال ایتا', '@zhikgold'),
('instagram_channel', 'کانال اینستگرام', 'zhikgold.ir'),
('address', 'آدرس', 'قم، خیابان توحید، بین کوچه 9 و میدان توحید، پاساژ علی ابن موسی الرضا (ع)، طبقه زیر همکف، انتهای سالن، طلای ژیک'),
('cart_duration_validity', 'مدت زمان اعتبار قیمت سبد خرید', '180'),
('access_token', 'توکن دسترسی جیبیت', 'eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2ppYml0LmlyIiwiYXVkIjoiaWRlbnRpY2F0b3IiLCJzdWIiOiI0T3ZqeSIsImV4cCI6MTc2MTM4NDYwMCwiYWNjZXNzIjp0cnVlfQ.KAA4aONHHu8zGLhLDRNVSKzu-nGooZE466B9Z-OqQqo2q2mznyB_ZivEo3Pq7dGSN8aQlyWxvH26v2HsHveebw'),
('refresh_token', 'توکن بازیابی جیبیت', 'eyJhbGciOiJIUzUxMiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL2ppYml0LmlyIiwiYXVkIjoiaWRlbnRpY2F0b3IiLCJzdWIiOiI0T3ZqeSIsImV4cCI6MTc2MTQ3MTAwMCwicmVmcmVzaCI6dHJ1ZX0.EJNTgTS-2kW6Yjom3q0Sq_kprmeAVbY91E82omabb18HDHg9xzqXR13O0yWaZl8AtJ3DtrtIwYaTzT5UxMrn1A'),
('payment_deadline', 'مهلت پرداخت', '900'),
('limited_amount_payable_by_gateway', 'حداکثر مبلغ قابل پرداخت توسط درگاه بانکی', '200000000'),
('working_hours', 'ساعات کاری', '[{\"start\":10,\"end\":13},{\"start\":17,\"end\":21}]'),
('send_notification_message_when_order_stored', 'ارسال پیامک اطلاع رسانی هنگام ثبت سفارش', '{\"status\":\"active\",\"phone_numbers\":[{\"id\":1730373740882,\"phone\":\"09396360199\",\"status\":\"active\"},{\"id\":1730383031270,\"phone\":\"09123753475\",\"status\":\"active\"}]}'),
('send_notification_message_when_order_confirmed', 'ارسال پیامک اطلاع رسانی هنگام تایید شدن سفارش', 'active'),
('send_notification_message_when_order_ready_for_delivery', 'ارسال پیامک اطلاع رسانی هنگام آماده تحویل شدن سفارش', 'active'),
('send_notification_message_when_order_ready_to_sent', 'ارسال پیامک اطلاع رسانی هنگام آماده ارسال شدن سفارش', 'active'),
('send_notification_message_when_order_has_been_sent', 'ارسال پیامک اطلاع رسانی هنگام ارسال شدن سفارش', 'active'),
('cost_per_matching_inquiry', 'هزینه تطابق کد ملی با کارت یا شبا', '1200'),
('cost_per_similarity_inquiry', 'هزینه استعلام ثبت احوال مقایسه‌ای', '1500'),
('cost_per_shahkar_inquiry', 'هزینه تطابق کد ملی با شماره موبایل (شاهکار)', '1400'),
('value_added_tax', 'مالیات بر ارزش افزوده', '0.1'),
('min_melted_gold_order', 'حداقل سفارش آبشده بصورت اتومات', '1'),
('max_price_api_calls', 'حداکثر تعداد فراخوانی ای‌پی‌آی قیمت', '2000'),
('max_market_api_calls', 'حداکثر تعداد فراخوانی ای‌پی‌آی مارکت', '2000'),
('melted_gold_validity_period', 'مدت اعتبار قیمت طلای آبشده', '600'),
('validity_period_of_melted_order_before_expires', 'مدت اعتبار سفارش آبشده قبل از منقضی شدن', '120'),
('reference_channel_id', 'کانال مرجع', '1'),
('min_order_send_to_exchange', 'حداقل سفارش جهت ارسال به صرافی', '1'),
('send_notification_message_when_melted_order_rejected', 'ارسال پیامک اطلاع رسانی در هنگام رد شدن سفارش‌ بصورت اتومات', '{\"status\":\"inactive\",\"phone_numbers\":[{\"id\":1730373740882,\"phone\":\"09396360199\",\"status\":\"active\"},{\"id\":1730383031270,\"phone\":\"09123753475\",\"status\":\"active\"}]}'),
('custom_rate_buy_sell_diff', 'اختلاف خرید و فروش فردایی', '100000'),
('auto_send_order_to_exchange', 'ثبت سفارش اتومات', 'active'),
('market_status', 'وضعیت بازار', 'active'),
('max_order_send_to_exchange', 'حداکثر سفارش جهت ارسال به صرافی', '1000'),
('min_price_difference_alert_notification', 'حداقل اختلاف قیمت جهت اعلان هشدار در آبشده نقد فردا', '200000'),
('tomorrow_spot_settlement_buy', 'فروش ما', 'active'),
('tomorrow_spot_settlement_sell', 'خرید ما', 'active'),
('cost_per_iban_or_card_inquiry', 'هزینه استعلام شماره شبا یا کارت', '500'),
('cost_per_iban_from_card_inquiry', 'هزینه استعلام شماره شبا توسط شماره کارت', '700'),
('today_spot_settlement_buy', 'فروش ما', 'inactive'),
('today_spot_settlement_sell', 'خرید ما', 'active'),
('day_after_tomorrow_spot_settlement_buy', 'فروش ما', 'active'),
('day_after_tomorrow_spot_settlement_sell', 'فروش ما', 'active'),
('today_spot_settlement_buy_margin', 'تلرانس خرید ما به نسبت آبشده فردا', '-300000'),
('today_spot_settlement_sell_margin', 'تلرانس فروش ما به نسبت آبشده فردا', '-300000'),
('display_today_spot_settlement_tolerance_on_main_tab', 'نمایش تلرانس آبشده نقد حاضر در تنظیمات اصلی', 'active'),
('display_day_after_tomorrow_spot_settlement_tolerance_on_main_tab', 'نمایش تلرانس آبشده نقد پس فردا در تنظیمات اصلی', 'active'),
('min_today_spot_settlement_order', 'حداقل سفارش آبشده نقد حاضر ', '1'),
('max_today_spot_settlement_order', 'حداکثر سفارش آبشده نقد حاضر', '1000'),
('custom_day_after_tomorrow_rate_buy_sell_diff', 'اختلاف خرید و فروش پس فردایی', '100000'),
('min_price_difference_alert_notification_for_day_after_tomorrow', 'حداقل اختلاف قیمت جهت اعلان هشدار در آبشده نقد پس فردا', '200000'),
('gold_coin_86_buy', 'فروش ما', 'active'),
('gold_coin_86_sell', 'خرید ما', 'active'),
('custom_gold_coin_86_rate_buy_sell_diff', 'اختلاف خرید و فروش سکه 86', '1000000'),
('min_price_difference_alert_notification_for_gold_coin_86', 'حداقل اختلاف قیمت جهت اعلان هشدار در سکه 86', '200000'),
('gold_half_coin_86_buy', 'فروش ما', 'active'),
('gold_half_coin_86_sell', 'خرید ما', 'active'),
('custom_gold_half_coin_86_rate_buy_sell_diff', 'اختلاف خرید و فروش نیم سکه 86', '1000000'),
('min_price_difference_alert_notification_for_gold_half_coin_86', 'حداقل اختلاف قیمت جهت اعلان هشدار در نیم سکه 86', '200000'),
('gold_quarter_coin_86_buy', 'فروش ما', 'active'),
('gold_quarter_coin_86_sell', 'خرید ما', 'active'),
('custom_gold_quarter_coin_86_rate_buy_sell_diff', 'اختلاف خرید و فروش ربع سکه 86', '1000000'),
('min_price_difference_alert_notification_for_gold_quarter_coin_86', 'حداقل اختلاف قیمت جهت اعلان هشدار در ربع سکه 86', '200000'),
('gold_coin_old_version_buy', 'فروش ما', 'active'),
('gold_coin_old_version_sell', 'خرید ما', 'active'),
('custom_gold_coin_old_version_rate_buy_sell_diff', 'اختلاف خرید و فروش سکه قدیم', '1000000'),
('min_price_difference_alert_notification_for_gold_coin_old_version', 'حداقل اختلاف قیمت جهت اعلان هشدار در سکه قدیم', '200000'),
('market_opening_notification', 'اطلاع رسانی باز شدن بازار', 'active'),
('submit_outbound_gold_orders_by_bot', 'ثبت خودکار سفارشات آبشده در سایر طلافروشی‌ها توسط ربات', 'inactive'),
('default_metal_trader_group_id', 'گروه پیش فرض معاملاتی کلاینت‌ها', ''),
('molten_page_metal_item_id', 'فلز مورد استفاده برای صفحه آبشده سایت', ''),
('jewelry_sale_hedge_metal_item_id', 'فلز مورد استفاده برای خرید پس از فروش طلای زینتی', ''),
('auto_order_dispatch_enabled', 'وضعیت کلی ثبت سفارش خودکار', '1'),
('manual_order_review_duration_seconds', '(ثانیه) زمان بررسی قبل از آغاز روند خودکار', '30'),
('melted_stock_quantity', 'موجودی آبشده', '0'),
('min_melted_stock_quantity', 'حداقل موجودی آبشده', '3'),
('max_melted_stock_quantity', 'حداکثر موجودی آبشده', '20');
